### ISSUE TITLE
Alchemist should be creating data folders automatically

### ISSUE THREAD

**Issue by DanySK** [AlchemistSimulator/Alchemist#128]
if Alchemist is launched with the `-e` flag on a non-existing path, it does not try to create it.

Example failure:

```
Exception in thread "main" java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.io.FileNotFoundException: data/simulation_seed-0.0_meanTaskSize-1_sm
oothing-0.01_grain-1300.0_peakFrequency-0.001.txt (No such file or directory)
        at it.unibo.alchemist.AlchemistRunner.launch(AlchemistRunner.java:188)
        at it.unibo.alchemist.Alchemist.main(Alchemist.java:141)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.io.FileNotFoundException: data/simulation_seed-0.0_meanTaskSize-1_smoothing-0.01_grain-1300.0_peakFrequency-0.001.txt
 (No such file or directory)
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at it.unibo.alchemist.AlchemistRunner.launchLocal(AlchemistRunner.java:215)
        at it.unibo.alchemist.AlchemistRunner.launch(AlchemistRunner.java:160)
        ... 1 more
Caused by: java.lang.IllegalStateException: java.io.FileNotFoundException: data/simulation_seed-0.0_meanTaskSize-1_smoothing-0.01_grain-1300.0_peakFrequency-0.001.txt (No such file or directory)
        at it.unibo.alchemist.AlchemistRunner.lambda$prepareSimulations$11(AlchemistRunner.java:317)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)   
Caused by: java.io.FileNotFoundException: data/simulation_seed-0.0_meanTaskSize-1_smoothing-0.01_grain-1300.0_peakFrequency-0.001.txt (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126)
        at java.base/java.io.PrintStream.<init>(PrintStream.java:266)
        at it.unibo.alchemist.loader.export.Exporter.<init>(Exporter.java:59)
        at it.unibo.alchemist.AlchemistRunner.lambda$prepareSimulations$11(AlchemistRunner.java:314)
        ... 4 more
```

**Comment by DanySK** [comment]
This has been fixed already.
