### ISSUE TITLE
Variable substitution does not work for "incarnation" in Alchemist YAML

### ISSUE THREAD

**Issue by metaphori** [AlchemistSimulator/Alchemist#46]
YAML to reproduce:

<pre>
variables:
  incarnation: &incarnation
    min: 0
    max: 1
    step: 1
    default: 0
  incarnationToUse: &incarnationToUse
    formula: 'if($incarnation==0) "Scafi" else "Protelis"'
    language: scala

incarnation: *incarnationToUse
</pre>

Error:
<pre>
Exception in thread "main" java.lang.IllegalStateException: {formula=if($incarnation==0) "Scafi" else "Protelis", language=scala} is not a valid incarnation. Supported incarnations are: [scafi, biochemistry, sapere, protelis]
        at it.unibo.alchemist.loader.YamlLoader.lambda$new$3(YamlLoader.java:231)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at it.unibo.alchemist.loader.YamlLoader.<init>(YamlLoader.java:229)
        at it.unibo.alchemist.loader.YamlLoader.<init>(YamlLoader.java:203)
        at it.unibo.alchemist.Alchemist.main(Alchemist.java:89)
</pre>

**Comment by DanySK** [comment]
I investigated this. Although I realize it may be useful in some cases, it creates a loop in the configuration file process: incarnations are required to resolve some kind of variables, but at the same time they may be a variable themselves. Considering that this is an extremely corner case (simulations varying incarnation!), I am currently this and marking the issue as wontfix.
Please let me know if you find many cases in which this feature is required.
