### ISSUE TITLE
Impossible create new project

### ISSUE THREAD

**Issue by Placu95** [AlchemistSimulator/Alchemist#49]
Trying to create new Alchemist project, after select the incarnation and click on Finish, an error is generated:
`java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
...
Caused by: java.lang.NullPointerException
	at it.unibo.alchemist.boundary.projectview.controller.NewProjLayoutSelectController.resourcesFrom(NewProjLayoutSelectController.java:143)
	at it.unibo.alchemist.boundary.projectview.controller.NewProjLayoutSelectController.copyRecursively(NewProjLayoutSelectController.java:100)
	at it.unibo.alchemist.boundary.projectview.controller.NewProjLayoutSelectController.clickFinish(NewProjLayoutSelectController.java:120)
	... 124 more`

**Comment by Placu95** [comment]
Solved in feature-gpx commit 9828f35
